/**
 * The product's identity, in one dependency-free module the manifest, the icon
 * generator and the editor can all import. `style.css` and the `theme-color`
 * meta in `index.html` cannot import, so they carry literal copies.
 */

/** Chrome and plate colour. */
export const INK = '#1b1d21'
/** The accent: the app mark, and the colour you draw with by default. */
export const ACCENT = '#e2483d'
export const PAPER = '#ffffff'

export interface IconSpec {
  file: string
  size: number
  /** Fill the whole square: platforms crop maskable and iOS icons themselves. */
  bleed: boolean
  /** Listed in the web manifest. iOS takes its icon from a `<link>` instead. */
  inManifest: boolean
  purpose?: 'maskable'
}

/** Generated by `scripts/make-icons.mjs`, declared to the manifest by `vite.config.ts`. */
export const ICONS: readonly IconSpec[] = [
  { file: 'icon-192.png', size: 192, bleed: false, inManifest: true },
  { file: 'icon-512.png', size: 512, bleed: false, inManifest: true },
  { file: 'icon-maskable-512.png', size: 512, bleed: true, inManifest: true, purpose: 'maskable' },
  { file: 'apple-touch-icon.png', size: 180, bleed: true, inManifest: false },
]
