/**
 * The one place the product's identity is written down.
 *
 * These values cross several boundaries that no compiler checks -- the web
 * manifest, the icon generator, the default drawing colour -- so they live in a
 * dependency-free module that all three can import. (`src/style.css` and the
 * `<meta name="theme-color">` in `index.html` still carry literal copies;
 * neither can import, and both are noted there.)
 */

/** Chrome and plate colour. */
export const INK = '#1b1d21'
/** The accent: the app mark, and the colour you draw with by default. */
export const ACCENT = '#e2483d'
export const PAPER = '#ffffff'

export interface IconSpec {
  file: string
  size: number
  /** Fill the whole square: platforms crop maskable and iOS icons themselves. */
  bleed: boolean
  /** Listed in the web manifest. iOS takes its icon from a `<link>` instead. */
  inManifest: boolean
  purpose?: 'maskable'
}

/** Generated by `scripts/make-icons.mjs`, declared to the manifest by `vite.config.ts`. */
export const ICONS: readonly IconSpec[] = [
  { file: 'icon-192.png', size: 192, bleed: false, inManifest: true },
  { file: 'icon-512.png', size: 512, bleed: false, inManifest: true },
  { file: 'icon-maskable-512.png', size: 512, bleed: true, inManifest: true, purpose: 'maskable' },
  { file: 'apple-touch-icon.png', size: 180, bleed: true, inManifest: false },
]
